{"uuid": "976dece8-8e44-497e-ae77-d1d6ef9bb725", "children": ["aa07febc-921c-47d8-be7e-59d283407c28", "e7b1eaf9-eeaf-4f91-966e-e8011c26a260", "05e58834-177a-4390-a229-cdb19dd0f918", "c5595e4e-b610-4c64-be85-91f6b6b2d163", "cfa61883-5ff4-427f-95c8-17dcc82e1cf6", "8dea87db-167e-4d06-9720-a44aa8060680", "fbefa2f2-39dd-4acd-94e5-d26f511d03f3", "ab6c529b-d422-49e5-bee2-e85355275be5", "8521e631-6f00-4c21-ad94-b800fc60c0b0", "52a9a10b-8e5c-4a17-85a9-2196c8729033", "4131106a-d6e4-4d8e-90f6-0ac0ddeb817c"], "befores": [{"name": "stop", "status": "passed", "start": 1651092916661, "stop": 1651092916661}], "afters": [{"name": "stop::fin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection\n\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\allure_commons\\_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\conftest.py\", line 57, in fin\n    fixture.session.ensure_logout()\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\session.py\", line 25, in ensure_logout\n    if self.is_logget_in():\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\session.py\", line 30, in is_logget_in\n    return len(wd.find_elements_by_link_text(\"Logout\")) > 0\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in find_elements_by_link_text\n    return self.find_elements(by=By.LINK_TEXT, value=text)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1283, in find_elements\n    return self.execute(Command.FIND_ELEMENTS, {\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1651092972464, "stop": 1651092972505}], "start": 1651092916661, "stop": 1651092972505}