{"uuid": "8c30b384-8422-4220-ac57-1898f3d4a9cc", "children": ["fbefa2f2-39dd-4acd-94e5-d26f511d03f3", "ab6c529b-d422-49e5-bee2-e85355275be5", "8521e631-6f00-4c21-ad94-b800fc60c0b0", "52a9a10b-8e5c-4a17-85a9-2196c8729033", "4131106a-d6e4-4d8e-90f6-0ac0ddeb817c"], "befores": [{"name": "db", "status": "broken", "statusDetails": {"message": "pymysql.err.OperationalError: (2003, \"Can't connect to MySQL server on 'localhost' ([WinError 10061] Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение)\")\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\conftest.py\", line 40, in db\n    dbfixture = DbFixture(host=db_config['host'], name=db_config['name'], user=db_config['user'], password=db_config['password'])\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\db.py\", line 13, in __init__\n    self.connection = pymysql.connect(host=host, database=name, user=user, password=password, autocommit=True)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\pymysql\\connections.py\", line 353, in __init__\n    self.connect()\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\pymysql\\connections.py\", line 664, in connect\n    raise exc\n"}, "start": 1651092969684, "stop": 1651092971701}], "start": 1651092969684, "stop": 1651092972448}